[phases.setup]
nixPkgs = ["nodejs-20_x"]

[phases.install]
cmds = [
    "npm install",
    "cd client && npm install"
]

[phases.build]
cmds = ["cd client && npm run build"]

[start]
cmd = "npm start"
